language: java

jdk:
    - oraclejdk8
    
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install oracle-java8-installer

notifications:
    webhooks:
        urls:
            - secure: "TV+fOlVPjkVhh8Otqs2GwV1PMTy1CZL+sd380C894fF7SAEwCfFIxQ+ZV/BDPAl4g+uzMujuLy0rjiIPX3UEyU/Sxh2pD3Cqp1RsICHRgwUFDR3rap0gTTHXVoB8NpPY1GIjevYP8C7cTLg1TeeW6cBk0u/WeMABpxnGttabMsA="
        on_success: always
        on_failure: always
        on_start: false

deploy:
  provider: releases
  api-key: 
      secure: "jDndeOwSkZqGDpzV5LGrgKggx4eupG4Wtfsz1+X35iL/6NGD9skXhhhFIg4VvV9NQ0DulA7euWUGPq8ERkFYBasWfrwMzUSwZIzGO0X/cHodKK+PGFtxX+aBE5DkknqQH/PR758c1d9U8eNBXQj48SFXAdpfGQBXJ00dyRt1KgY="
  file:
      - "target/algorithm-converter-0.1.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    #must remain on all_branches: true together with tags: true due to the following bug: https://github.com/travis-ci/travis-ci/issues/1675
    #ideal situation would be to change it such that it only builds a release on the master branch on tag push